export const actionTypes = {
    SET_POKEMON_DATA: 'SET_POKEMON_DATA',
    SET_CHARACTER_SELECT: 'SET_CHARACTER_SELECT',
    SET_SELECTED_TAB: 'SET_SELECTED_TAB',
    SET_ON_SOUND: 'SET_ON_SOUND',
    SET_ON_LOAD_DESCRIPTION: 'SET_ON_LOAD_DESCRIPTION',
    SET_TAB_DESCRIPTION_DATA: 'SET_TAB_DESCRIPTION_DATA',
    CHANGE_LOADING: 'CHANGE_LOADING',
    SET_SHINNY_ON: 'SET_SHINNY_ON',
    SET_FAMALE_ON: 'SET_FAMALE_ON',
    SET_AUTO_SOUND: 'SET_AUTO_SOUND',
    SET_ENABLE_EFFECT: 'SET_ENABLE_EFFECT',
    SET_LEGENDARY: 'SET_LEGENDARY',
    LOAD_POKEMON_CARD: 'LOAD_POKEMON_CARD'
  }