export const actionTypes = {
    CARGAR_POKEMONS: 'CARGAR_POKEMONS',
    SET_GENERACION: 'SET_GENERACION',
    SET_POKEDEX_PAGE: 'SET_POKEDEX_PAGE',
    SET_SEARCH: 'SET_SEARCH',
    CARGAR_POKEMONS_HOME_PAGE: 'CARGAR_POKEMONS_HOME_PAGE',
  }